# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6fbb230f05c5fd6a1c201d064009d279"
application_url = "https://www.app.sheldonai.net"
embedded = true
name = "SheldonAI"
handle = "sheldonai"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, write_orders"

[auth]
redirect_urls = [
  "https://sheldon-ai-ruby.vercel.app/auth/callback",
  "https://sheldon-ai-ruby.vercel.app/auth/shopify/callback",
  "https://sheldon-ai-ruby.vercel.app/api/auth/callback"
]
[pos]
embedded = false
